
CREATE DATABASE IF NOT EXISTS mvp;

CREATE TABLE IF NOT EXISTS mvp.t_member
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    password TEXT        NOT NULL,
    role     INTEGER     NOT NULL DEFAULT 99,
    EXTEND_JSON TEST
);